@media print {
            @page { /*size: portrait;*/ margin:0.5cm; margin-top: 0.5cm; }
            
            .pbBody {     margin: 7px 0px 7px !important; }
            .charts-div { margin-left: 0px !important; }
            .overall-history { margin-top: 0px;  }
            .page-break { height: 60px; page-break-before: always; }
            .header-info-table-page2 { float: right; width: 50%; padding-top: 0px; }
            .bPageTitle-page2 { float: left; width: 50%; }
        }