/*Page Description:
*  Test class for DS_Functioning_Forms_B
*
* Last Updated on:
* 7/23/2014
* Update Purpose:
* condense all BASELINE2 tests 
* restructuring
* batch testing
* compatibility
9/10-re-separated individual form methods for easier updating
* Programmer:
*  Kelsey
*/
@isTest
private class TestClass_DS_Functioning_Forms_B{
    
    /*static TestMethod void Test_TestInsertUpdateDelete() {
        TestClass_A_Utility test_ut = new TestClass_A_Utility();
        Client__c client = test_ut.createClientSummary();
        ///begin bulk insert
        List<DS_Functioning_Forms_B__c> bulkObj = new List<DS_Functioning_Forms_B__c>();     
        for (Integer i=0;i<200;i++){
            bulkObj.add(new DS_Functioning_Forms_B__c(client__c = client.id));
        }
        insert bulkObj;
        ///end bulk insert   
    }*/
    
    
}