@isTest
public class TestClassData_DS_PTSD_Form_Info{

  public TestClassData_DS_PTSD_Form_Info() {
    
    List<List<String>> FormInfo = new List<List<String>>();
        
 //FormInfo.add(new List<String> {'Type__c','Section__c','Content__c','Number__c','Field__c','Symptom__c', 'Data_Type__c',  'Object__c',  'Form__c', 'File_name__c' });
 
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I am on the lookout for danger or things that I am afraid of.','1','PTSV1','E3','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have thoughts like I am a bad.','2','PTSV2','D2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I try to stay away from people, places or things remind me about what happened.','3','PTSV3','C2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I get upset easily or get into arguments or physical fights.','4','PTSV4','E1','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel like I am back at the time when the bad thing happened, like it\'s happening all over again.','5','PTSV5','B3','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel like what happened was sickening or gross.','6','PTSV6','D4','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I don\'t feel like doing things with my family or friends or other things that I liked to do.','7','PTSV7','D5','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have trouble concentrating or paying attention.','8','PTSV8','E5','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','"I have thoughts like, The world is really dangerous."','9','PTSV9','D2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have bad dreams about what happened or other bad dreams.','10','PTSV10','B2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','When something reminds me of what happened I get very upset, afraid or sad.','11','PTSV11','B4','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have trouble feeling happiness or love.','12','PTSV12','D7','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I try not to think about or have feelings about what happened.','13','PTSV13','C1','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','When something reminds me of what happened, I have strong feelings in my body like my heart beats fast, my head aches or my stomach aches.','14','PTSV14','B5','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I am mad with someone for making the bad thing happen, not doing more to stop it or to help after.','15','PTSV15','D3','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have thoughts like I will never be able to trust other people.','16','PTSV16','D2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel alone even when I am around other people.','17','PTSV17','D6','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','"I have upsetting thoughts, pictures or sounds of what happened come into my mind when I don\'t want them to."','18','PTSV18','B1','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel that part of what happened was my fault.','19','PTSV19','D3','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I hurt myself on purpose.','20','PTSV20','E2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have trouble going to sleep, wake up often or have trouble getting back to sleep.','21','PTSV21','E6','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel ashamed or embarrassed over what happened.','22','PTSV22','D4','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I have trouble remembering important parts of what happened.','23','PTSV23','D1','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel jumpy or startle easily, like when I hear a loud noise or when something surprises me.','24','PTSV24','E4','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel afraid or scared.','25','PTSV25','D4','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I do risky or unsafe things that could really hurt me or someone else.','26','PTSV26','E2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I want to get back at someone for what happened.','27','PTSV27','D4','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','TRUE','Dissociative Subtype','27.5','','','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel like I am seeing myself or what I am doing from outside my body.','28','PTSV28','A1','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel not connected to my body, like I\'m not really there inside.','29','PTSV29','A1','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel like things around me look strange, different or like I am in a fog.','30','PTSV30','A2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});
    FormInfo.add(new List<String> {'Children / Adolescents','FALSE','I feel like things around me are not real, like I am in a dream.','31','PTSV31','A2','DS_PTSD_Form_Info','DS_PTSD_CA_B','DS_PTSD_CA','BASELINE'});

  //  List<DS_PTSD_Form_Info__c> infoBox = new List<DS_PTSD_Form_Info__c>();
    List<DS_DATA__c> infoBox = new List<DS_DATA__c>();

    for(List<String> f : FormInfo) {

    //  DS_PTSD_Form_Info__c info = new DS_PTSD_Form_Info__c();
      DS_DATA__c info = new DS_DATA__c();
   
 //FormInfo.add(new List<String> {'Type__c','Section__c','Content__c','Number__c','Field__c','Symptom__c', 'Data_Type__c',  'Object__c',  'Form__c', 'File_name__c' });
 
      info.Type__c = f.get(0);
      info.Section__c = Boolean.valueOf(f.get(1));
      info.Content__c = f.get(2);
      info.Number__c = Decimal.valueOf(f.get(3));
      info.Field__c = f.get(4);
      info.Symptom__c = f.get(5);
      info.Data_Type__c = f.get(6);
      info.Object__c = f.get(7); 
      info.Form__c = f.get(8);
      info.File_name__c = f.get(9);
 

      infoBox.add(info);

    }

    List<DS_DATA__c> checkForm = [SELECT id 
                                    FROM DS_DATA__c 
                                   WHERE Data_Type__c = 'DS_PTSD_Form_Info'];

    if(checkForm.size() == 0) insert infoBox;
        
  }
    
}