@isTest
public class TestClassData_DS_Variable{

  public TestClassData_DS_Variable(){
    
    List<List<String>> varInfo = new List<List<String>>();
          
    
    //varInfo.add(new List<String> {'Data_Type__c','Codelist','File name','Long Description','Object','Source form','Variable label','Variable name','Variable number','Variable type'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','"8. Feeding Conditions e.g., eats non-foods, has swallowing difficulties, etc."','DS BACKGROUND FAMILY INFO B','HEALTH','Feeding Conditions is health condition','BHISFEED','8','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','9. GI Problems is the health status','DS BACKGROUND FAMILY INFO B','HEALTH','GI Problems is health condition','BHISGI','9','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','10. Headaches is the health status','DS BACKGROUND FAMILY INFO B','HEALTH','Headaches is health condition','BHISHED','10','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','11. Heart Conditions is the health status','DS BACKGROUND FAMILY INFO B','HEALTH','Heart Conditions is health condition','BHISHRT','11','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','12. Physical Impairment is the health status','DS BACKGROUND FAMILY INFO B','HEALTH','Physical impairment is health condition','BHISPYSI','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','13. Recurrent Ear Infections','DS BACKGROUND FAMILY INFO B','HEALTH','Recurrent ear infections is health condition','BHISEI','13','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','14. Seizure/Convulsions Problems','DS BACKGROUND FAMILY INFO B','HEALTH','Seizure/Convulsions is health condition','BHISSEZ','14','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','15. Weight Issues is the health status','DS BACKGROUND FAMILY INFO B','HEALTH','Weight Issuesis health condition','BHISWT','15','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','16. Weightloss/Weight Gain/ Thyroid Problems','DS BACKGROUND FAMILY INFO B','HEALTH','Weight loss/Weight Gain is health condition','BHISWTLS','16','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTHTH','BASELINE','17. Other is the health status','DS BACKGROUND FAMILY INFO B','HEALTH','Other is health condition','BHISOTHR','17','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','<None>','BASELINE','17. Other Please specify','DS BACKGROUND FAMILY INFO B','HEALTH','Other Specified','BHISOTSP','17','CHAR50'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTYNUN','BASELINE','2. Childs course of treatment','DS BACKGROUND FAMILY INFO B','HEALTH','None is treatment','BTRT','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','2. Oral medication is the treatment','DS BACKGROUND FAMILY INFO B','HEALTH','Oral Medication is treatment','BTRTOMED','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','2. Injections is the treatment','DS BACKGROUND FAMILY INFO B','HEALTH','Injections is the treatment','BTRTINJ','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','2. Physical limitation is the treatment','DS BACKGROUND FAMILY INFO B','HEALTH','Physical limitations is the treatment','BTRTPL','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','2. Prescribed diet is the treatment','DS BACKGROUND FAMILY INFO B','HEALTH','Perscribed diet is the treatment','BTRTPD','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','2. Other','DS BACKGROUND FAMILY INFO B','HEALTH','Other','BTRTOTHR','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','<None>','BASELINE','2. Other specified treatment','DS BACKGROUND FAMILY INFO B','HEALTH','Other Specified','BTRTOTSP','2','CHAR50'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','2. Unknown treatment','DS BACKGROUND FAMILY INFO B','HEALTH','Unknown','BTRTUK','2','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTYNUN','BASELINE','3. Services Beyond Primary Care Recieved','DS BACKGROUND FAMILY INFO B','HEALTH','None is the service','BHSR','3','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','3. Hospital is the healthcare service','DS BACKGROUND FAMILY INFO B','HEALTH','Hospital is the service','BHSRHOS','3','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','3. Emergency Department is the healthcare service','DS BACKGROUND FAMILY INFO B','HEALTH','Emergency Department is the service','BHSRED','3','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','3. Surgery is the healthcare service','DS BACKGROUND FAMILY INFO B','HEALTH','Surgery is the service','BHSRSUR','3','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','3. Urgent Care is the healthcare service','DS BACKGROUND FAMILY INFO B','HEALTH','Urgent Care is the service','BHSRUC','3','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','3. Occupational Therapy is the service','DS BACKGROUND FAMILY INFO B','HEALTH','Occupational Therapy is the service','BHSROT','3','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','3. Unknown services','DS BACKGROUND FAMILY INFO B','HEALTH','Unknown is the service','BHSRUK','3','NUMBER'});

    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = Health Department','DS BACKGROUND FAMILY INFO B','DEMO','Health Department','BRHCHD','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = Hospital Clinic','DS BACKGROUND FAMILY INFO B','DEMO','Hospital Clinic','BRHCHC','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = Community Health Center','DS BACKGROUND FAMILY INFO B','DEMO','Community Health Center','BRHCCH','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = Private Doctor/HMO','DS BACKGROUND FAMILY INFO B','DEMO','Private Doctor/HMO','BRHCPD','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = other','DS BACKGROUND FAMILY INFO B','DEMO','Other','BRHCO','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','<None>','BASELINE','12. Please indicate where your child gets regular health care. = other specified','DS BACKGROUND FAMILY INFO B','DEMO','"Other, specified"','BRHCOSP','12','CHAR50'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = No regular place','DS BACKGROUND FAMILY INFO B','DEMO','No regular place','BRHCNONE','12','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','12. Please indicate where your child gets regular health care. = Unknown','DS BACKGROUND FAMILY INFO B','DEMO','Unknown','BRHCUK','12','NUMBER'});

    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of adult Mother','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Mother','BLMOTHER','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of Adult Father','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Father','BLFATHER','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of adult Parents Partner','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Parents Partner','BLPARTNR','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of Adult Grandparents','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Grandparents','BLGRAND','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1. Type of adult Other Adult Relative','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Other Adult Relative','BLOREL','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of adult Non-Relative','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Non-Relative','BLNONREL','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of adult Unknown','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Unknown','BLUNK','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','ZYES','BASELINE','1.  Type of adult Other','DS BACKGROUND FAMILY INFO B','DOMENV','Child lives with Other adult','BLOTHR','1','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','<None>','BASELINE','1.  Type of adult Other Specified','DS BACKGROUND FAMILY INFO B','DOMENV','Other adult Specified','BLOTHRSP','1','CHAR50'});

    varInfo.add(new List<String> {'DS_VARIABLE','CTCBCL','BASELINE','56B. Headaches','DS CBCL B','CBCL_6_18','Headaches','BCBO56B','56b','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTCBCL','BASELINE','"56C. Nausea, feels sick"','DS CBCL B','CBCL_6_18','"Nausea, feels sick"','BCBO56C','56c','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTCBCL','BASELINE','56D. Problems with eyes not if corrected by glasses','DS CBCL B','CBCL_6_18','Problems with eyes not if corrected by glasses','BCBO56D','56d','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTCBCL','BASELINE','56E. Rashes or other skin problems','DS CBCL B','CBCL_6_18','Rashes or other skin problems','BCBO56E','56e','NUMBER'});
    varInfo.add(new List<String> {'DS_VARIABLE','CTCBCL','BASELINE','56F. Stomachaches','DS CBCL B','CBCL_6_18','Stomach aches','BCBO56F','56f','NUMBER'});

    List<DS_DATA__c> infoBox = new List<DS_DATA__c>();

    for(List<String> f : varInfo) {
    
      DS_DATA__c info = new DS_DATA__c(); 

      info.Data_Type__c = f.get(0);
      info.CODELIST__c = f.get(1);
      info.FILE_NAME__c = f.get(2);
      info.LONG_DESCRIPTION__c = f.get(3);
      info.Object__c = f.get(4);
      info.SOURCE_FORM__c = f.get(5);
      info.VARIABLE_LABEL__c = f.get(6);
      info.VARIABLE_NAME__c = f.get(7);
      info.VARIABLE_NUMBER__c = f.get(8);
      info.VARIABLE_TYPE__c = f.get(9);

      infoBox.add(info);

    }

    List<DS_DATA__c> checkForm = [SELECT id 
                                    FROM DS_DATA__c 
                                   WHERE Data_type__c = 'DS_DS_VARIABLE'];
  
    if(checkForm.size() == 0) insert infoBox;

    //insert infoBox;

    System.debug(infoBox);

  }
    
}