Age_Range__c,Category__c,CODE__c,Codelist__c,Content__c,Data_Type__c,Describe_Field__c,Field__c,File_name__c,Form__c,Gender__c,Gender_Required__c,Long_Description__c,LONGLABEL__c,Note__c,Number__c,Object__c,Page__c,Percentile__c,Question_Field__c,Raw_Score__c,Scale__c,Scale_Number__c,Section__c,Sig_Range__c,Source_form__c,Symptom__c,T_Score__c,Type__c,Variable__c,Variable_label__c,Variable_name__c,Variable_number__c,Variable_type__c,Variable_value__c,Weight__c
7_18,Assessment,,,UCLA PTSD Reaction Index Child/Adolescent Version,DS_Form_Info,,,BASELINE,DS_PTSD_CA,,FALSE,,,,,DS_PTSD_CA_B,DS_PTSD_CA,,,,,,FALSE,,,,,,DS_PTSD_CA,,,,,,1
,TD,,,War/Terrorism/Political Violence Outside the U.S.,DS_Form_Info,,,,,,FALSE,,,(Exposure to any of these events outside of the U.S.),,DS_TRDETAIL1,DS_TRWAROUTSIDEUS,,,,,,FALSE,,,,,,GT10R,,,,,,10
,TD,,,War/Terrorism/Political Violence Inside the U.S.,DS_Form_Info,,,,,,FALSE,,,(Exposure to any of these events inside the U.S.),,DS_TRDETAIL1,DS_TRWAR,,,,,,FALSE,,,,,,GT9R,,,,,,9
,TD,,,Extreme Interpersonal Violence (Not Reported Elsewhere),DS_Form_Info,,,,,,FALSE,,,"(e.g., Homicide/suicide)",,DS_TRDETAIL2,DS_TRVIOLENCE,,,,,,FALSE,,,,,,GT19R,,,,,,19
,TD,,,Sexual Assault/Rape,DS_Form_Info,,,,,,FALSE,,,"(Actual or attempted sexual molestation, exploitation, or coercion not by a caregiver and not recorded as sexual abuse)",,DS_TRDETAIL1,DS_TRSEXASSAULT,,,,,,FALSE,,,,,,GT2R,,,,,,2
,TD,,,Sexual Maltreatment/Abuse,DS_Form_Info,,,,,,FALSE,,,"(Actual or attempted sexual molestation, exploitation, or coercion by a caregiver)",,DS_TRDETAIL1,DS_TRSEX,,,,,,FALSE,,,,,,GT1R,,,,,,1
,TD,,,Serious Accident/Injury,DS_Form_Info,,,,,,FALSE,,,(Unintentional accident or injury),,DS_TRDETAIL1,DS_TRACCIDENT,,,,,,FALSE,,,,,,GT12R,,,,,,12
,TD,,,Separation,DS_Form_Info,,,,,,FALSE,,,(Separation of  a primary caregiver or sibling),,DS_TRDETAIL2,DS_TRSEPARATION,,,,,,FALSE,,,,,,GT16R,,,,,,16
,TD,,,School Violence (Not Reported Elsewhere),DS_Form_Info,,,,,,FALSE,,,"(e.g., School shooting, bullying, classmate suicide)",,DS_TRDETAIL2,DS_TRSCHOOLVIO,,,,,,FALSE,,,,,,GT21R,,,,,,21
,TD,,,Psychological or Emotional Maltreatment/Abuse,DS_Form_Info,,,,,,FALSE,,,"(Verbal abuse, excessive demands, emotional neglect)",,DS_TRDETAIL1,DS_TRPSYCHABUSE,,,,,,FALSE,,,,,,GT6R,,,,,,6
,TD,,,Physical Assault,DS_Form_Info,,,,,,FALSE,,,(Actual or attempted infliction of physical pain or bodily injury not by a caregiver and not recorded as physical abuse ),,DS_TRDETAIL1,DS_TRPHYSASSAULT,,,,,,FALSE,,,,,,GT5R,,,,,,5
,TD,,,Other Trauma,DS_Form_Info,,,,,,FALSE,,,,,,DS_TROTHER,,,,,,FALSE,,,,,,GT23R,,,,,,23
,TD,,,Neglect,DS_Form_Info,,,,,,FALSE,,,"(Physical, medical, or educational neglect)",,DS_TRDETAIL1,DS_TRNEGLECT,,,,,,FALSE,,,,,,GT7R,,,,,,7
,TD,,,Disaster (Natural and Manmade),DS_Form_Info,,,,,,FALSE,,,(Major accident or disaster that is the result of a natural or manmade event),,DS_TRDETAIL1,DS_TRNATURALDIS,,,,,,FALSE,,,,,,GT13R,,,,,,13
,TD,,,Illness/Medical Trauma,DS_Form_Info,,,,,,FALSE,,,(Life threatening or extremely painful illness or medical procedure),,DS_TRDETAIL1,DS_TRMEDICAL,,,,,,FALSE,,,,,,GT11R,,,,,,11
,TD,,,Kidnapping/Abduction,DS_Form_Info,,,,,,FALSE,,,(Unlawful seizure or detention against the child's will),,DS_TRDETAIL2,DS_TRKIDNAP,,,,,,FALSE,,,,,,GT14R,,,,,,14
,TD,,,Impaired Caregiver,DS_Form_Info,,,,,,FALSE,,,"(History of exposure to caretaker depression, other medical illness, or alcohol/drug abuse)",,DS_TRDETAIL2,DS_TRIMPCARE,,,,,,FALSE,,,,,,GT18R,,,,,,18
,TD,,,Domestic Violence,DS_Form_Info,,,,,,FALSE,,,"(Exposure to physical, sexual, and/or emotional abuse directed at adult caregiver(s) in the home)",,DS_TRDETAIL1,DS_TRDOMVIO,,,,,,FALSE,,,,,,GT8R,,,,,,8
,TD,,,Forced Displacement,DS_Form_Info,,,,,,FALSE,,,(Forced relocation due to political reasons),,DS_TRDETAIL2,DS_TRDISPLACE,,,,,,FALSE,,,,,,GT17R,,,,,,17
,TD,,,Community Violence (Not Reported Elsewhere),DS_Form_Info,,,,,,FALSE,,,"(e.g., Gang-related violence, neighborhood violence)",,DS_TRDETAIL2,DS_TRCOMMVIO,,,,,,FALSE,,,,,,GT20R,,,,,,20
,TD,,,Trafficking,DS_Form_Info,,,,,,FALSE,,,"(Child has been offered, obtained, or engaged in any kind of sexual activity in exchange for anything of value, money, goods, personal benefit, in-kind favors, or some other kind of benefit)",,DS_TRDETAIL1,DS_TRCOMMEXP,,,,,,FALSE,,,,,,GT3R,,,,,,3
,TD,,,Bullying,DS_Form_Info,,,,,,FALSE,,,(Unwanted aggressive behavior among school aged children that involves a real or perceived power imbalance),,DS_TRDETAIL2,DS_TRBULLYING,,,,,,FALSE,,,,,,GT22R,,,,,,22
,TD,,,Bereavement,DS_Form_Info,,,,,,FALSE,,,"(Death or separation of  a primary caregiver or sibling; the unexpected, or premature death of a close relative or close friend)",,DS_TRDETAIL2,DS_TRBEREAVE,,,,,,FALSE,,,,,,GT15R,,,,,,15
,TD,,,Physical Maltreatment/Abuse,DS_Form_Info,,,,,,FALSE,,,(Actual or attempted infliction of physical pain or bodily injury by a caregiver),,DS_TRDETAIL1,DS_TRABUSE,,,,,,FALSE,,,,,,GT4R,,,,,,4
,GT,,,General Trauma Information Form,DS_Form_Info,,,BASELINE,,,FALSE,,,,,DS_GTRAUMA,DS_GTRAUMA,,,,,,FALSE,,,,,,GT,,,,,,
7_18,Assessment,,,UCLA PTSD Reaction Index Child/Adolescent Version,DS_Form_Info,,,FOLLOWUP,DS_PTSD_CA,,FALSE,,,,,DS_PTSD_CA_F,DS_PTSD_CA,,,,,,FALSE,,,,,,DS_PTSD_CA,,,,,,1
,FollowUp,,,Brief Intervention Services Information,DS_Form_Info,,,FOLLOWUP,DS_BIS,,FALSE,,,,,DS_Functioning_Forms_F,DS_BIS,,,,,,FALSE,,BIS,,,,DS_BIS,,,,,,3
,Baseline,,,Brief Intervention Services Information,DS_Form_Info,,,BASELINE,DS_BIS,,FALSE,,,,,DS_Functioning_Forms_B,DS_BIS,,,,,,FALSE,,BIS,,,,DS_BIS,,,,,,13
,FollowUp,,,NCTSN Breakthrough Series/ Learning Collaborative(s),DS_Form_Info,,,FOLLOWUP,DS_BSLC,,FALSE,,,,,DS_Functioning_Forms_F,DS_BSLC,,,,,,FALSE,,BSLC,,,,DS_BSLC,,,,,,4
,Baseline,,,NCTSN Breakthrough Series/ Learning Collaborative(s),DS_Form_Info,,,BASELINE,DS_BSLC,,FALSE,,,,,DS_Functioning_Forms_B,DS_BSLC,,,,,,FALSE,,BSLC,,,,DS_BSLC,,,,,,14
3_21,FollowUp,,,CANS Strengths Assessment (Clinician Rating) - Children Ages 3 and Above,DS_Form_Info,,,FOLLOWUP,DS_CANSTR,,FALSE,,,,,DS_Functioning_Forms_F,DS_CANSTR,,,,,,FALSE,,CANSTR,,,,DS_CANSTR,,,,,,13
3_21,Baseline,,,CANS Strengths Assessment (Clinician Rating) - Ages 3 and Above,DS_Form_Info,,,BASELINE,DS_CANSTR,,FALSE,,,,,DS_Functioning_Forms_B,DS_CANSTR,,,,,,FALSE,,CANSTR,,,,DS_CANSTR,,,,,,11
,FollowUp,,,Clinical Evaluation,DS_Form_Info,,,FOLLOWUP,DS_CLINEVAL,,FALSE,,,,,DS_Functioning_Forms_F,DS_CLINEVAL,,,,,,FALSE,,CLINEVAL,,,,DS_CLINEVAL,,,,,,14
,Baseline,,,Clinical Evaluation,DS_Form_Info,,,BASELINE,DS_CLINEVAL,,FALSE,,,,,DS_Functioning_Forms_B,DS_CLINEVAL,,,,,,FALSE,,CLINEVAL,,,,DS_CLINEVAL,,,,,,12
,Baseline,,,Baseline Visit and Demographic Information,DS_Form_Info,,,BASELINE,DS_DEMO,,FALSE,,,,,DS_Background_Family_Info_B,DS_DEMO,,,,,,FALSE,,DEMO,,,,DS_DEMO,,,,,,1
,FollowUp,,,"Domestic Environment, Domestic Environment Details, and Education",DS_Form_Info,,,FOLLOWUP,DS_DOMENV,,FALSE,,,,,DS_Background_Family_Info_F,DS_DOMENV,,,,,,FALSE,,DOMENV,,,,DS_DOMENV,,,,,,7
,Baseline,,,"Domestic Environment, Domestic Environment Details, and Education",DS_Form_Info,,,BASELINE,DS_DOMENV,,FALSE,,,,,DS_Background_Family_Info_B,DS_DOMENV,,,,,,FALSE,,DOMENV,,,,DS_DOMENV,,,,,,4
1.5_5,Assessment,,,Child Behavior Checklist - Ages 1.5-5,DS_Form_Info,,,FOLLOWUP,DS_CBCL_0_5,,TRUE,,,,,DS_CBCL_F,DS_CBCL_0_5,,,,,,FALSE,,DS_CBCL_0_5,,,,DS_CBCL_0_5,,,,,,2
1.5_5,Assessment,,,Child Behavior Checklist - Ages 1.5-5,DS_Form_Info,,,BASELINE,DS_CBCL_0_5,,TRUE,,,,,DS_CBCL_B,DS_CBCL_0_5,,,,,,FALSE,,DS_CBCL_0_5,,,,DS_CBCL_0_5,,,,,,2
6_18,Assessment,,,Child Behavior Checklist - Ages 6-18,DS_Form_Info,,,FOLLOWUP,DS_CBCL_6_18,,TRUE,,,,,DS_CBCL_F,DS_CBCL_6_18,,,,,,FALSE,,DS_CBCL_6_18,,,6_18,DS_CBCL_6_18,,,,,,3
6_18,Assessment,,,Child Behavior Checklist - Ages 6-18,DS_Form_Info,,,BASELINE,DS_CBCL_6_18,,TRUE,,,,,DS_CBCL_B,DS_CBCL_6_18,,,,,,FALSE,,DS_CBCL_6_18,,,6_18,DS_CBCL_6_18,,,,,,3
,FollowUp,,,Family Assessment Module - Family APGAR (Caregiver Report),DS_Form_Info,,,FOLLOWUP,DS_FAPGAR,,FALSE,,,,,DS_Functioning_Forms_F,DS_FAPGAR,,,,,,FALSE,,FAPGAR,,,,DS_FAPGAR,,,,,,12
,Baseline,,,Family Assessment Module - Family APGAR (Caregiver Report),DS_Form_Info,,,BASELINE,DS_FAPGAR,,FALSE,,,,,DS_Functioning_Forms_B,DS_FAPGAR,,,,,,FALSE,,FAPGAR,,,,DS_FAPGAR,,,,,,10
,FollowUp,,,Follow-Up Information,DS_Form_Info,,,FOLLOWUP,DS_FOLLOWUPINFO,,FALSE,,,,,DS_Background_Family_Info_F,DS_FOLLOWUPINFO,,,,,,FALSE,,FOLLOWUPINFO,,,,DS_FOLLOWUPINFO,,,,,,1
,FollowUp,,,Health Module,DS_Form_Info,,,FOLLOWUP,DS_HEALTH,,FALSE,,,,,DS_Background_Family_Info_F,DS_HEALTH,,,,,,FALSE,,HEALTH,,,,DS_HEALTH,,,,,,5
,Baseline,,,Health Module,DS_Form_Info,,,BASELINE,DS_HEALTH,,FALSE,,,,,DS_Background_Family_Info_B,DS_HEALTH,,,,,,FALSE,,HEALTH,,,,DS_HEALTH,,,,,,2
6_21,FollowUp,,,Indicators of Severity of Problems - Children 6 and Above,DS_Form_Info,,,FOLLOWUP,DS_INDSEV,,FALSE,,,,,DS_Functioning_Forms_F,DS_INDSEV,,,,,,FALSE,,INDSEV,,,,DS_INDSEV,,,,,,8
6_21,Baseline,,,Indicators of Severity of Problems,DS_Form_Info,,,BASELINE,DS_INDSEV,,FALSE,,,,,DS_Functioning_Forms_B,DS_INDSEV,,,,,,FALSE,,INDSEV,,,,DS_INDSEV,,,,,,5
,FollowUp,,,Insurance Information,DS_Form_Info,,,FOLLOWUP,DS_INSDOMENV,,FALSE,,,,,DS_Background_Family_Info_F,DS_INSDOMENV,,,,,,FALSE,,INSDOMENV,,,,DS_INSDOMENV,,,,,,6
,Baseline,,,Insurance Information,DS_Form_Info,,,BASELINE,DS_INSDOMENV,,FALSE,,,,,DS_Background_Family_Info_B,DS_INSDOMENV,,,,,,FALSE,,INSDOMENV,,,,DS_INSDOMENV,,,,,,3
,FollowUp,,,Military Families Form,DS_Form_Info,,,FOLLOWUP,DS_MILITARY,,FALSE,,,,,DS_Background_Family_Info_F,DS_MILITARY,,,,,,FALSE,,MILITARY,,,,DS_MILITARY,,,,,,11
,Baseline,,,Military Families Form,DS_Form_Info,,,BASELINE,DS_MILITARY,,FALSE,,,,,DS_Background_Family_Info_B,DS_MILITARY,,,,,,FALSE,,MILITARY,,,,DS_MILITARY,,,,,,9
,FollowUp,,,Treatment by NCTSN Center,DS_Form_Info,,,FOLLOWUP,DS_NCTSNTREAT,,FALSE,,,,,DS_Background_Family_Info_F,DS_NCTSNTREAT,,,,,,FALSE,,NCTSNTREAT,,,,DS_NCTSNTREAT,,,,,,2
,Baseline,,,NOMs,DS_Form_Info,,,BASELINE,DS_NOMS,,FALSE,,,,,DS_Functioning_Forms_B,DS_NOMS,,,,,,FALSE,,NOMS,,,,DS_NOMS,,,,,,15
,Baseline,,,Refugee and Immigrant Families Form,DS_Form_Info,,,BASELINE,DS_REFIMM,,FALSE,,,,,DS_Background_Family_Info_B,DS_REFIMM,,,,,,FALSE,,REFIMM,,,,DS_REFIMM,,,,,,8
,FollowUp,,,Services Received Since Last CIMI Assessment,DS_Form_Info,,,FOLLOWUP,DS_SERVREC,,FALSE,,,,,DS_Functioning_Forms_F,DS_SERVREC,,,,,,FALSE,,SERVREC,,,,DS_SERVREC,,,,,,10
,Baseline,,,Services Received,DS_Form_Info,,,BASELINE,DS_SERVREC,,FALSE,,,,,DS_Functioning_Forms_B,DS_SERVREC,,,,,,FALSE,,SERVREC,,,,DS_SERVREC,,,,,,7
0_5,FollowUp,,,Young Child Indicators of Severity of Problems - Children Under 6,DS_Form_Info,,,FOLLOWUP,DS_YCINDSEV,,FALSE,,,,,DS_Functioning_Forms_F,DS_YCINDSEV,,,,,,FALSE,,YCINDSEV,,,,DS_YCINDSEV,,,,,,9
0_5,Baseline,,,Young Child Indicators of Severity of Problems- Children Under 6,DS_Form_Info,,,BASELINE,DS_YCINDSEV,,FALSE,,,,,DS_Functioning_Forms_B,DS_YCINDSEV,,,,,,FALSE,,YCINDSEV,,,,DS_YCINDSEV,,,,,,6
4_10,Assessment,,,Strengths and Difficulties Questionnaire for Parents 4-10,DS_Form_Info,,,FOLLOWUP,DS_SDQ_P_04_10,,FALSE,,,,,DS_SDQ_PSI_CDI_F,DS_SDQ_P_04_10,,,,,,FALSE,,DS_SDQ_P_04_10,,,,DS_SDQ_P_04_10,,,,,,4
4_10,Assessment,,,Strengths and Difficulties Questionnaire for Parents 4-10,DS_Form_Info,,,BASELINE,DS_SDQ_P_04_10,,FALSE,,,,,DS_SDQ_PSI_CDI_B,DS_SDQ_P_04_10,,,,,,FALSE,,DS_SDQ_P_04_10,,,,DS_SDQ_P_04_10,,,,,,4
11_17,Assessment,,,Strengths and Difficulties Questionnaire for Parents 11-17,DS_Form_Info,,,FOLLOWUP,DS_SDQ_P_11_17,,FALSE,,,,,DS_SDQ_PSI_CDI_F,DS_SDQ_P_11_17,,,,,,FALSE,,DS_SDQ_P_11_17,,,,DS_SDQ_P_11_17,,,,,,5
11_17,Assessment,,,Strengths and Difficulties Questionnaire for Parents 11-17,DS_Form_Info,,,BASELINE,DS_SDQ_P_11_17,,FALSE,,,,,DS_SDQ_PSI_CDI_B,DS_SDQ_P_11_17,,,,,,FALSE,,DS_SDQ_P_11_17,,,,DS_SDQ_P_11_17,,,,,,5
11_17,Assessment,,,Strengths and Difficulties Questionnaire Self-Assessment 11-17,DS_Form_Info,,,FOLLOWUP,DS_SDQ_S_11_17,,FALSE,,,,,DS_SDQ_PSI_CDI_F,DS_SDQ_S_11_17,,,,,,FALSE,,DS_SDQ_S_11_17,,,,DS_SDQ_S_11_17,,,,,,6
11_17,Assessment,,,Strengths and Difficulties Questionnaire Self-Assessment 11-17,DS_Form_Info,,,BASELINE,DS_SDQ_S_11_17,,FALSE,,,,,DS_SDQ_PSI_CDI_B,DS_SDQ_S_11_17,,,,,,FALSE,,DS_SDQ_S_11_17,,,,DS_SDQ_S_11_17,,,,,,6
