Age_Range__c,Category__c,CODE__c,Codelist__c,Content__c,Data_Type__c,Describe_Field__c,Field__c,File_name__c,Form__c,Gender__c,Gender_Required__c,Long_Description__c,LONGLABEL__c,Note__c,Number__c,Object__c,Page__c,Percentile__c,Question_Field__c,Raw_Score__c,Scale__c,Scale_Number__c,Section__c,Sig_Range__c,Source_form__c,Symptom__c,T_Score__c,Type__c,Variable__c,Variable_label__c,Variable_name__c,Variable_number__c,Variable_type__c,Variable_value__c,Weight__c
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,Please note that this trauma type requires perpetration by someone in the role of a caregiver.<br>For Trafficking please skip to that section (page 5).<br>Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,SECTION,,,"<strong>The next questions apply to children who experienced an illness/medical trauma, only.</Strong>",DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RWPN,,,,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RWPN,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RWEAPON,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RWEAPON,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RWEAPON,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RWEAPON,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RWEAPON,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RWEAPON,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,9
,RWEAPON,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RWEAPON,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RWEAPON,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RVTYP,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RTYPDS,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RTYP,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRDISPLACE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRIMPCARE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTYP,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,RTVIO,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RTT12C,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RTR,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,10
,RTHI,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RST,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RSET4,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RSET3,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET3,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RSET2,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RREPORT,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RREPORT,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RREPORT,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RREPORT,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RSET1,,,What type of care did this illness/medical procedure include? <b>(Select all that apply.)</b>,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RSE,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RREUN,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RRESIB,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RRES,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RREPORT,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RREPORT,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,11
,RREPORT,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,9
,RREPORT,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RRE,,,,DS_TD_Form_Info,,,,TRDISPLACE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RPR2,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RPR,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RPICU,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,9
,RPER4,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER3,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RPER,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER2,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RPER,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RPER,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RPENET,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,9
,RPENET,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,9
,RPAIN,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RNTYPES,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RMTYP,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RMEN,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RMED,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RLIFE,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ4,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RINJ3,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ2,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RINJ2,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RFREQ,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RINJ,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ,,,Was anyone that the child knew seriously injured or killed?,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RINJ,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RINJ,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RINJ,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RINC,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RIN,,,Did this assault/rape involve any of the following?  <b>(Select all that apply.)</b>,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,10
,RIN,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,10
,RIMP,,,,DS_TD_Form_Info,,,,TRIMPCARE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RILL,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RHDAM,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RGANG,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RFTB,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RFREQ,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFRGT,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,8
,RFREQ,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRDISPLACE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRIMPCARE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,RFREQ,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,2
,REVAC,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RDV,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RDU,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RDIS,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,7
,RD,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RCP,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,5
,RCMP,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,9
,RCG,,,,DS_TD_Form_Info,,,,TRIMPCARE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,4
,RBEN,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RBASE,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRSEX,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRDISPLACE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRIMPCARE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRVIOLENCE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RBASE,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,1
,RSRV,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,6
,RTYP,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,,,,,,,,,,FALSE,,,,,,,,,,,,3
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRSEPARATION,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRDOMVIO,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRNEGLECT,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRDISPLACE,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRWAR,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRWAROUTSIDEUS,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRSCHOOLVIO,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRNATURALDIS,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRSEXASSAULT,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.<br/>For Commercial Sexual Exploitation please skip to that section (page 5).,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRACCIDENT,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRBEREAVE,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRCOMMEXP,,FALSE,,,"Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.  Please use this form to provide detail on a child who has been offered, obtained, or engaged in any kind of trafficking.",,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRPSYCHABUSE,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRPHYSASSAULT,,FALSE,,,"Please note that this trauma type requires perpetration by someone in the role of a caregiver. 
Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.",,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRCOMMVIO,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRKIDNAP,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRABUSE,,FALSE,,,"Please note that this trauma type requires perpetration by someone in the role of a caregiver. 
Complete the following if experience of this trauma type is indicated on the General Trauma Information Form",,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRMEDICAL,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRBULLYING,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
,INSTRUCTION,,,,DS_TD_Form_Info,,,,TRIMPCARE,,FALSE,,,Complete the following if experience of this trauma type is indicated on the General Trauma Information Form.,,,,,,,,,FALSE,,,,,,,,,,,,0
